[package]
name = "many-bin"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cargo-many-bin"

[dependencies]

[package.manifest.dist]
dist = false
