name: Release

permissions:
  contents: write
  
on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  # Create the Github Release™ so the packages have something to be uploaded to
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: blah
        run: |
          echo "i ran!"


